address potential strict aliasing violation
veorq/SipHash pull request #35
Opened 2021-02-20 19:51 UTC by veorq

2021-03-10 22:14 UTC, gsauthof requested changes

2021-03-10 22:14 UTC, gsauthof commented on halfsiphash.c
> +    unsigned char *kk = (unsigned char *)k;
You cast away the `const` qualifier which conflicts with the role of that pointer.

So what about:

```
    const unsigned char *ni = (const unsigned char *)in;
￼    const unsigned char *kk = (const unsigned char *)k;
```

For C compiler only compatibility, you could even leave out the cast on the right hand side.

2021-03-10 22:14 UTC, gsauthof commented on halfsiphash.c
> +    const uint8_t *end = ni + inlen - (inlen % sizeof(uint32_t));
This should also be:

```
const unsigned char *end = ni + inlen - (inlen % sizeof(uint32_t));
```

2021-03-10 22:14 UTC, gsauthof commented on siphash.c
> +    unsigned char *kk = (unsigned char *)k;
As above, `const unsigned char *ni ... const unsigned char *kk ...`, etc.

2021-03-10 22:14 UTC, gsauthof commented on siphash.c
> +    const uint8_t *end = ni + inlen - (inlen % sizeof(uint64_t));
As above, `const unsigned char *end = ...`.

2021-03-12 07:30 UTC, veorq commented
Thanks @gsauthof for catching these, no fixed, we should be good to go!

2021-03-12 07:30 UTC, merged